config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "pages#show", page: "home"

  devise_for :users, skip: [:sessions, :registrations], controllers: { invitations: "invitations" }

  devise_scope :user do
    resources :users
    
    delete 'users/:id/deactivate',  to: 'users#cancel', as: :deactivate_user
    patch 'users/:id/status',  to: 'users#resource_state_change', as: :user_resource_state_change
    patch 'users/:id/role',  to: 'users#resource_role_change', as: :user_resource_role_change
    get 'account', to: 'users#show', as: :account
    get 'account/edit', to: 'users#edit', as: :edit_account
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  get 'projects/calendar', to: 'calendar#index', as: :projects_calendar, resources: { projects: 'Project' }
  resources :roles
  resources :groups, :projects, :documents, :tasks do
    patch 'status', action: :resource_state_change, as: :resource_state_change
  end

  as :project do
    get 'account/schedule', to: 'projects#schedule_index', as: :schedule
    get 'account/projects', to: 'projects#user_projects_index', as: :user_projects
  end

  as :group do
    get 'account/groups', to: 'groups#user_groups_index', as: :user_groups
  end

  # Nested routes with multiple or unknown parents
  scope as: :nested do
    scope '/:resource_controller' do
      scope '/:resource_id'do
        resources :tasks
        resources :notes
        resources :roles
        resources :documents

        scope module: :nested do
          resources :users do
            patch 'role', action: :resource_role_change, as: :resource_role_change
          end
        end
      end
    end
  end
end

app/models/concerns/notes/notable.rb
module Concerns::Notes::Notable
    # Remove this and call upon the module's methods to include instead to fix performance hit
    def self.included(source)
        source.class_eval do
            has_many :notes, as: :loggable
            accepts_nested_attributes_for :notes, reject_if: :all_blank, allow_destroy: true
        end
        
        define_instance_methods(source)
    end

    # Performance hit: Avoids falseClass empty stop along the call chain - https://8thlight.com/blog/josh-cheek/2012/02/03/modules-called-they-want-their-integrity-back.html
    def define_instance_methods(source = self)
        source.class_eval do
            # Returns a boolean which evaluates to true if the note count in RAM is greater than in the DB
            def note_added?
                persisted_count = self.notes.count
                ram_count = self.notes.to_a.count
                ram_count > persisted_count
            end
            
            # Validation method
            def note_was_added
                errors.add(:notes, "must be added") unless note_added?
            end
        end
    end

    extend self
end

app/models/note.rb
class Note < Log
  include Concerns::Polymorphic::Helpers
  
  belongs_to :loggable, polymorphic: true, optional: true
  belongs_to :user

  validates :user, presence: true
  
  def author
    user.name
  end
end

app/controllers/concerns/notes/nested/set_author.rb
module Concerns::Notes::Nested::SetAuthor
  
  private
  
    # This method is used to find the note or note_attributes node and update the author to current_user
    def set_author
      model = controller_name.singularize.downcase
      if model == "note"
        params[model][:user_id] = current_user.id
      elsif params[model].key? :notes_attributes
        params[model][:notes_attributes].each do |note|
          params[model][:notes_attributes][note][:user_id] = current_user.id
        end
      end
    end
end

app/controllers/notes_controller.rb
class NotesController < Flexible::ResourceController
  include Concerns::Notes::Nested::SetAuthor

  before_action :authenticate_user!
  before_action :set_author, only: [:create, :update]

  private

    def note_params
      params.require(:note).permit(:text, :user_id)
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for @note, url: @note.persisted? ? nested_note_path : nested_notes_path do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= render 'note_fields', f: f %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<tr>
  <td><%= note.loggable_type %></td>
  <td><%= note.text %></td>
  <td><%= note.author %></td>
  <td><%= note.created_at %></td>

  <td>
    <%= link_to nested_note_path(note.polymorphic_resource.class.name.downcase.pluralize, note.polymorphic_resource, note.id) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
    <% end %>
  </td>

  <td>
    <%= link_to edit_nested_note_path(note.polymorphic_resource.class.name.downcase.pluralize, note.polymorphic_resource, note.id) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to nested_note_path(note.polymorphic_resource.class.name.downcase.pluralize, note.polymorphic_resource, note.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/notes/_note_attributes.html.erb
<p>
  <strong>Text:</strong>
  <%= note.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= note.author %>
</p>

app/views/notes/_note_fields.html.erb
<div class="container-fluid">
    <div class="form-group row">
        <%= f.label :text, class: "form-label control-label col-md-2" %>
        <%= f.text_area :text, class: "form-control no-border-radius" %>
    </div>

    <%= render 'shared/nested/remove_button', f: f %>
</div>

app/views/notes/edit.html.erb
<% title('Editing Note by ' @note.author) %>
<%= content_tag :h1, 'Editing Note by ' @note.author %>

<%= render 'form', note: @note %>

<%= link_to 'Show', nested_note_path(id: @note) %> |
<%= link_to 'Back', @resource %>

app/views/notes/index.html.erb
<% title('Notes') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <h1 class="no-margin">Notifications</h1>
    </div>

    <div class="col-md-2 text-center">
      <%= link_to new_nested_note_path(params[:resource_controller] || controller_name, params[:id] || params[:resource_id]) do %>
        <%= fa_icon "plus", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>Text</th>
      <th>Author</th>
      <th>Create At</th>
      <th>Info</th>
      <th>Edit</th>
      <th>Delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @notes %>
  </tbody>
</table>

app/views/notes/new.html.erb
<% title('New Note') %>
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', nested_notes_path %>

app/views/notes/show.html.erb
<% title('Note by ' + @note.author) %>
<%= content_tag :h1, 'Note by ' + @note.author %>

<%= render 'note_attributes', note: @note %>

<%= link_to 'Edit', edit_nested_note_path(id: @note) %> |
<%= link_to 'Back', @resource %>