config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "pages#show", page: "home"

  devise_for :users, skip: [:sessions, :registrations], controllers: { invitations: "invitations" }

  devise_scope :user do
    resources :users
    
    delete 'users/:id/deactivate',  to: 'users#cancel', as: :deactivate_user
    patch 'users/:id/status',  to: 'users#resource_state_change', as: :user_resource_state_change
    patch 'users/:id/role',  to: 'users#resource_role_change', as: :user_resource_role_change
    get 'account', to: 'users#show', as: :account
    get 'account/edit', to: 'users#edit', as: :edit_account
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  get 'projects/calendar', to: 'calendar#index', as: :projects_calendar, resources: { projects: 'Project' }
  resources :roles
  resources :groups, :projects, :documents, :tasks do
    patch 'status', action: :resource_state_change, as: :resource_state_change
  end

  as :project do
    get 'account/schedule', to: 'projects#schedule_index', as: :schedule
    get 'account/projects', to: 'projects#user_projects_index', as: :user_projects
  end

  as :group do
    get 'account/groups', to: 'groups#user_groups_index', as: :user_groups
  end

  # Nested routes with multiple or unknown parents
  scope as: :nested do
    scope '/:resource_controller' do
      scope '/:resource_id'do
        resources :tasks
        resources :notes
        resources :roles
        resources :documents

        scope module: :nested do
          resources :users do
            patch 'role', action: :resource_role_change, as: :resource_role_change
          end
        end
      end
    end
  end
end

app/models/concerns/tasks/taskable.rb
module Concerns::Tasks::Taskable
    # Remove this and call upon the module's methods to include instead to fix performance hit
    def self.included(source)
        source.class_eval do
            has_many :tasks, as: :taskable, dependent: :destroy
            accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
        end
    end

    extend self
end

app/models/task.rb
class Task < ApplicationRecord
    include Concerns::Polymorphic::Helpers
    include Concerns::Notes::Notable
    include Helpers::ResourceStateHelper
    
    belongs_to :taskable, polymorphic: true, optional: true

    validates :name, presence: true
    validate :note_was_added, if: lambda { transitioning_to_state?(:problem) }

    include AASM
    STATES = [:pending, :completed, :problem]
    aasm :column => 'resource_state', :with_klass => NorthwestTransferAASMBase do
        require_state_methods!

        STATES.map do |status|
            state(status, initial: STATES[0] == status)
        end

        event :complete do
            transitions to: :completed
        end

        event :report_problem, guards: :note_added? do
            transitions to: :problem
        end
    end

end

app/controllers/tasks_controller.rb
class TasksController < Flexible::ResourceController
  include Concerns::Notes::Nested::SetAuthor
  include Concerns::Resource::State::ResourceStateChange

  before_action :authenticate_user!
  before_action :set_author, only: [:create, :update]

  private

    def task_params
      params.require(:task).permit(:name,
                                    :description,
                                    :resource_state,
                                    notes_attributes: [:id, :text, :user_id, :_destroy])
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_display_tasks.html.erb
<%if object.class == Task %>
<tr>
  <td><%= object.name %></td>
  <td><%= object.description %></td>
  <td><%= object.aasm.current_state %></td>
  <td><%= link_to ("#{object}_path(id: #{object}") do %>
        <%= fa_icon "info-circle", class: "btn btn-default" %>
        <% end %></td>
  <td><%= link_to ("edit_#{object}_path(id: #{object})") do %>
        <%= fa_icon "pencil", class:"btn btn-success" %>
        <% end %></td>
  <td><%= link_to "#{object}_path(id: #{object}), method: :delete, data: { confirm: 'Are you sure?' }" do %>
    <%= fa_icon "trash", class:"btn btn-danger" %>
  <% end %></td>
</tr>
<% elsif object.class == User %>
  <tr>
    <td><%= fa_icon "user" %></td>
    <td><%= object.first_name %></td>
    <td><%= object.last_name %></td>
    <td><%= object.phone %></td>
    <td><%= object.email  %></td>
    <td><%= link_to ("edit_#{object}_path(id: #{object})") do %>
          <%= fa_icon "pencil", class:"btn btn-success" %>
          <% end %></td>
    <td><%= link_to "#{object}_path(id: #{object}), method: :delete, data: { confirm: 'Are you sure?' }" do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
      <% end %></td>
  </tr>
<% elsif object.class == Note %>
  <tr>
    <td><%= object.loggable_type %></td>
    <td><%= object.user.first_name %> <%= object.user.last_name %>, <%= object.created_at %> </td>
  </tr>
<% elsif object.class == Document %>
  <tr>
    <td><%= object.title %></td>
    <td><%= object.created_at %> </td>
    <td><%= link_to ("#{object}_path(id: #{object}") do %>
          <%= fa_icon "info-circle", class: "btn btn-default" %>
          <% end %></td>
    <td><%= link_to ("edit_#{object}_path(id: #{object})") do %>
          <%= fa_icon "pencil", class:"btn btn-success" %>
          <% end %></td>
    <td><%= link_to "#{object}_path(id: #{object}), method: :delete, data: { confirm: 'Are you sure?' }" do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
      <% end %></td>
  </tr>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for @task, url: @task.persisted? ? flexible_resource_path(:task_path, @task) : tasks_path do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'task_fields', f: f %>

  <%= f.fields_for :notes do |builder| %>
    <%= render 'notes/note_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields 'Add Note', f, :notes, { partial: 'notes/note_fields' } %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task-display.html.erb
<tr>
  <td><%= object.name %></td>
  <td><%= object.description %></td>
  <td><%= object.aasm.current_state %></td>

  <td>
    <%= link_to task_path("projects", @project, object) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
      <% end %>
  </td>

  <td>
    <%= link_to edit_task_path("projects", @project, object) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to task_path("projects", @project, object), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.aasm.current_state %></td>

  <td>
    <%= link_to nested_task_path(task.polymorphic_resource.class.name.downcase.pluralize, task.polymorphic_resource, task.id) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
    <% end %>
  </td>

  <td>
    <%= link_to edit_nested_task_path(task.polymorphic_resource.class.name.downcase.pluralize, task.polymorphic_resource, task.id) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to nested_task_path(task.polymorphic_resource.class.name.downcase.pluralize, task.polymorphic_resource, task.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/tasks/_task_fields.html.erb
<div class="container-fluid form-horizontal">
    <div class="form-group">
        <%= f.label :name, class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :name, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :description, class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :description, class: "form-control no-border-radius" %>
        </div>
    </div>

    <% if current_user.admin? %>
    <div class="form-group">
        <%= f.label :resource_state, I18n.t(:status).titleize, class: 'form-label control-label col-md-2'%>
        <div class="col-md-10 no-padding">
            <%= f.select :resource_state, resource_states(Task), { include_blank: true }, class: "form-control no-border-radius" %>
        </div>
    </div>
    <% end %>

    <%= render 'shared/nested/remove_button', f: f %>
</div>

app/views/tasks/edit.html.erb
<% title('Editing Task titled ' + @task.name) %>
<%= content_tag(:h1, 'Editing Task titled ' + @task.name) %>

<%= render 'form', task: @task %>

<%= link_to 'Show', flexible_resource_path(:task_path, @task) %> |
<%= link_to 'Back', @resource %>

app/views/tasks/index.html.erb
<% title('Tasks') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <h1 class="no-margin">Tasks</h1>
    </div>

    <div class="col-md-2 text-center">
      <%= link_to (params[:id] || params[:resource_id]).present? ? new_nested_task_path(params[:resource_controller] || controller_name, params[:id] || params[:resource_id]) : new_task_path do %>
        <%= fa_icon "plus", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <%= render @tasks %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<% title('New Task') %>
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', @resource %>

app/views/tasks/show.html.erb
<% title('Task titled ' + @task.name) %>
<%= content_tag(:h1, 'Task titled ' + @task.name) %>


<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.resource_state %>
</p>

<p>
  <strong>Notes</strong>
  <ol>
    <% @task.notes.each do |note| %>
    <li>
      <%= render 'notes/note_attributes', note: note %>
    </li>
    <% end %>
  </ol>
</p>

<div class="container">
  <%= render "shared/resource_state_actions", 
              object: @task, 
              button_class: "btn btn-default col-md-offset-4 col-md-4 buffer-margin-10" %>
</div>

<%= link_to 'Edit', flexible_resource_path(:edit_task_path, @task) %> |
<%= link_to 'Back', @resource %>