config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "pages#show", page: "home"

  devise_for :users, skip: [:sessions, :registrations], controllers: { invitations: "invitations" }

  devise_scope :user do
    resources :users
    
    delete 'users/:id/deactivate',  to: 'users#cancel', as: :deactivate_user
    patch 'users/:id/status',  to: 'users#resource_state_change', as: :user_resource_state_change
    patch 'users/:id/role',  to: 'users#resource_role_change', as: :user_resource_role_change
    get 'account', to: 'users#show', as: :account
    get 'account/edit', to: 'users#edit', as: :edit_account
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  get 'projects/calendar', to: 'calendar#index', as: :projects_calendar, resources: { projects: 'Project' }
  resources :roles
  resources :groups, :projects, :documents, :tasks do
    patch 'status', action: :resource_state_change, as: :resource_state_change
  end

  as :project do
    get 'account/schedule', to: 'projects#schedule_index', as: :schedule
    get 'account/projects', to: 'projects#user_projects_index', as: :user_projects
  end

  as :group do
    get 'account/groups', to: 'groups#user_groups_index', as: :user_groups
  end

  # Nested routes with multiple or unknown parents
  scope as: :nested do
    scope '/:resource_controller' do
      scope '/:resource_id'do
        resources :tasks
        resources :notes
        resources :roles
        resources :documents

        scope module: :nested do
          resources :users do
            patch 'role', action: :resource_role_change, as: :resource_role_change
          end
        end
      end
    end
  end
end

app/views/shared/_carousel.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
<!-- Indicators if wanted -->
<!-- <ol class="carousel-indicators">
  <li data-target="carousel" data-slide-to="0" class="active"></li>
  <li data-target="carousel" data-slide-to="1"></li>
  <li data-target="carousel" data-slide-to="2"></li>
  <li data-target="carousel" data-slide-to="3"></li>
  <li data-target="carousel" data-slide-to="4"></li>
</ol> -->
  <div id="carousel tabs">
    <ul class="nav nav-pills nav-justified">
      <!-- Make data-slide-to="0" into this data-slide-to="contacts" -->
      <li data-target="#carousel" data-slide-to="0" ><a href="#">Contacts</a></li>
      <li data-target="#carousel" data-slide-to="1"><a href="#">Notifacations</a></li>
      <li data-target="#carousel" data-slide-to="2"><a href="#">Tasks</a></li>
      <li data-target="#carousel" data-slide-to="3"><a href="#">Actions</a></li>
      <li data-target="#carousel" data-slide-to="4"><a href="#">Documents</a></li>
    </ul>
  </div>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <!--Slide 0, Contacts  -->
    <div class="item" >
        <%= render template: "users/index" %>
    </div>
    <!--Slide 1, Notifactions  -->
    <div class="item">
        <%= render template: "notes/index" %>
    </div>
    <!-- Slide 2, Tasks  -->
    <div class="item active">
      <div id="project_tasks">
        <%= render template: "tasks/index" %>
      </div>
    </div>
    <!-- Slide 3, Actions -->
    <div class="item">
        <%= render "shared/project_actions", object:project %>
    </div>
    <!-- Slide 4, Documents -->
    <div class="item">
        <%= render template: "documents/index" %>
    </div>
    <div class="carousel-side-navs">
      <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    <!-- end of carousel-inner -->
  </div>
</div>

app/views/shared/_clock.html.erb
<!-- _local_time_clock.js included -->
<div id="timebox" class="text-bold"></div>
<div id="datebox"></div>

app/views/shared/_document-display.html.erb
<tr>
  <td><%= object.title %></td>
  <td><%= object.signature %></td>
  <td><%= object.created_at %></td>
  <td><%= object.resource_state %></td>

  <td>
    <%= link_to document_path("projects", @project, object.id) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
    <% end %>
  </td>

  <td>
    <%= link_to edit_document_path("projects", @project, object.id) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to document_path("projects", @project, object.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="col-md-12 buffer-margin-20">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul class="text-left">
            <% object.errors.full_messages.each do |msg| %>
            <li class="text-danger"><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<% if Rails.env.development? %>
    <%= debug(params) %>
<% end %>

app/views/shared/_header.html.erb
<div class="container-fluid">
  <div class="row buffer-padding-20">
    <div class="col-md-6">
      <%= if content_for?(:header_badge) then yield(:header_badge) end %>
    </div>
    <div class="col-md-6">
      <div class="text-right font-size-200">
        <%= render 'shared/clock' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_note-display.html.erb
<tr>
  <td><%= object.loggable_type %></td>
  <td> <%= object.text %></td>
  <td><%= object.author %></td>
  <td><%= object.created_at %></td>

  <td>
    <%= link_to note_path("projects", @project, object.id) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
    <% end %>
  </td>

  <td>
    <%= link_to edit_note_path("projects", @project, object.id) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to note_path("projects", @project, object.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/shared/_resource_state_actions.html.erb
<% object.aasm.events.map do |event| %>
    <%= button_to I18n.t(event.name).titleize, 
        send("#{object.class.name.downcase}_resource_state_change_path", object), 
        method: :patch, params: { status_method: event.name.to_s }, 
        class: button_class unless event.instance_variable_get("@guards").include?(:state_user_admin?) && !current_user.admin? %>
<% end %>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>

<div class="nav-side-menu">
    <h2 class="brand no-margin">
        <span class="text-bold text-uppercase">NW</span> Transfer
    </h2>

    <div class="menu-list container-fluid">
        <ul id="menu-content" class="menu-content list-unstyled">
            <li data-toggle="collapse" data-target="#account" class="collapsed row cursor-pointer">
                <%= content_tag(:div, fa_icon("dashboard", text: "Account", class: "fa-lg"), class: "col-xs-10 buffer-padding-15") %>
                <%= fa_icon("angle-down", class: "fa-lg inline-block buffer-padding-15 col-xs-2") %>
            </li>
            <ul class="sub-menu collapse list-unstyled row" id="account">
                <%= content_tag(:li, link_to('My Account', account_path) ) %>
                <%= content_tag(:li, link_to('Edit Account', edit_account_path) ) %>
                <%= content_tag(:li, link_to('Logout', destroy_user_session_path, method: :delete) ) %>
            </ul>

            <li class="row">
                <%= link_to(fa_icon("th-list", text: "Schedule", class: "fa-lg"), schedule_path, class: "col-xs-12") %>
            </li>

            <li data-toggle="collapse" data-target="#groups" class="collapsed row cursor-pointer">
                <%= content_tag(:div, fa_icon("users", text: "Groups", class: "fa-lg"), class: "col-xs-10 buffer-padding-15") %>
                <%= fa_icon("angle-down", class: "fa-lg inline-block buffer-padding-15 col-xs-2") %>
            </li>
            <ul class="sub-menu collapse list-unstyled row" id="groups">
                <%= content_tag(:li, link_to('My Groups', user_groups_path) ) %>
                <%= content_tag(:li, link_to('All Groups (Admin)', groups_path) ) if current_user.has_role?(:admin) %>
            </ul>

            <li data-toggle="collapse" data-target="#products" class="collapsed row cursor-pointer">
                <%= content_tag(:div, fa_icon("cubes", text: "Projects", class: "fa-lg"), class: "col-xs-10 buffer-padding-15") %>
                <%= fa_icon("angle-down", class: "fa-lg inline-block buffer-padding-15 col-xs-2") %>
            </li>
            <ul class="sub-menu collapse list-unstyled row" id="products">
                <%= content_tag(:li, link_to('My Projects', user_projects_path) ) %>
                <%= content_tag(:li, link_to('Calendar', projects_calendar_path) ) %>
                <%= content_tag(:li, link_to('View All (Admin)', projects_path) ) if current_user.has_role?(:admin) %>
                <%= content_tag(:li, link_to('New Project (Admin)', new_project_path) ) if current_user.has_role?(:admin) %>
            </ul>

            <%= yield(:sidebar) %>

            <%= content_tag(:li, link_to(fa_icon("tag", text: "Users (Admin)", class: "fa-lg"), users_path, class: "col-xs-12" ), class: "row") if current_user.has_role?(:admin) %>
        </ul>
    </div>
</div>

<% end %>

app/views/shared/_user-display.html.erb
<tr>
  <td><%= object.first_name %></td>
  <td><%= object.last_name %></td>
  <td><%= object.phone %></td>
  <td><%= object.email  %></td>

  <td>
    <%= link_to edit_account_path(object.id) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to cancel_user_registration_path(object.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>