config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "pages#show", page: "home"

  devise_for :users, skip: [:sessions, :registrations], controllers: { invitations: "invitations" }

  devise_scope :user do
    resources :users
    
    delete 'users/:id/deactivate',  to: 'users#cancel', as: :deactivate_user
    patch 'users/:id/status',  to: 'users#resource_state_change', as: :user_resource_state_change
    patch 'users/:id/role',  to: 'users#resource_role_change', as: :user_resource_role_change
    get 'account', to: 'users#show', as: :account
    get 'account/edit', to: 'users#edit', as: :edit_account
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  get 'projects/calendar', to: 'calendar#index', as: :projects_calendar, resources: { projects: 'Project' }
  resources :roles
  resources :groups, :projects, :documents, :tasks do
    patch 'status', action: :resource_state_change, as: :resource_state_change
  end

  as :project do
    get 'account/schedule', to: 'projects#schedule_index', as: :schedule
    get 'account/projects', to: 'projects#user_projects_index', as: :user_projects
  end

  as :group do
    get 'account/groups', to: 'groups#user_groups_index', as: :user_groups
  end

  # Nested routes with multiple or unknown parents
  scope as: :nested do
    scope '/:resource_controller' do
      scope '/:resource_id'do
        resources :tasks
        resources :notes
        resources :roles
        resources :documents

        scope module: :nested do
          resources :users do
            patch 'role', action: :resource_role_change, as: :resource_role_change
          end
        end
      end
    end
  end
end

app/models/concerns/documents/documentable.rb
module Concerns::Documents::Documentable
    # Remove this and call upon the module's methods to include instead to fix performance hit
    def self.included(source)
        source.class_eval do
            has_many :documents, as: :documentable, dependent: :destroy
            accepts_nested_attributes_for :documents, reject_if: :all_blank, allow_destroy: true
        end
    end

    extend self
end

app/models/document.rb
class Document < ApplicationRecord
    include Concerns::Polymorphic::Helpers
    include Helpers::ResourceStateHelper
    belongs_to :documentable, polymorphic: true

    validates :title, presence: true
    
    include AASM
    STATES = [:pending, :completed, :deactivated]
    aasm :column => 'resource_state', :with_klass => NorthwestTransferAASMBase do
        require_state_methods!

        STATES.map do |status|
            state(status, initial: STATES[0] == status)
        end
        
        before_all_events :set_state_user
    
        event :complete, guards: :signed? do
            transitions to: :completed
        end
    
        event :deactivate, guards: :state_user_admin? do
            transitions to: :problem
        end
    end
    
    def signed?
       !self.signature.blank? && !self.completion_date.blank?
    end
end

app/controllers/documents_controller.rb
class DocumentsController < Flexible::ResourceController
  include Concerns::Resource::State::ResourceStateChange

  before_action :authenticate_user!

  private

    def document_params
      params.require(:document).permit(:title,
                                        :signature, 
                                        :resource_state, 
                                        :completion_date, 
                                        :customer_firstname, 
                                        :customer_lastname, 
                                        :ems_order_no, 
                                        :technician, 
                                        :shipper, 
                                        :make, 
                                        :brand, 
                                        :itm_model, 
                                        :age, 
                                        :itm_length, 
                                        :itm_width, 
                                        :itm_height, 
                                        :itm_name, 
                                        :itm_condition)
    end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<tr>
  <td><%= document.title %></td>
  <td><%= document.signature %></td>
  <td><%= document.created_at %></td>
  <td><%= document.resource_state %></td>

  <td>
    <%= link_to flexible_resource_path(:document_path, document) do %>
      <%= fa_icon "info-circle", class: "btn btn-default" %>
    <% end %>
  </td>

  <td>
    <%= link_to flexible_resource_path(:edit_document_path, document) do %>
      <%= fa_icon "pencil", class:"btn btn-success" %>
    <% end %>
  </td>

  <td>
    <%= link_to flexible_resource_path(:document_path, document), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon "trash", class:"btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/documents/_document_fields.html.erb
<div class="container-fluid form-horizontal">
    <div class="form-group">
        <%= f.label :title, class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :title, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :customer_firstname, "First Name", class: "form-label control-label col-md-2"%>
        <div class="col-md-10 no-padding">
            <%= f.text_field :customer_firstname, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :customer_lastname, "Last Name", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :customer_lastname, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :ems_order_no, "EMS Order No.", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.number_field :ems_order_no, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :technician, "Technician", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :technician, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :shipper, "Shipper", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :shipper, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_name, "Name of Item", class: "form-label control-label col-md-2"%>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_name, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_condition, "Condition", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_condition, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :make, "Make", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :make, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :brand, "Brand", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :brand, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_model, "Model", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_model, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :age, "Age of Item", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :age, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_length, "Length", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_length, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_width, "Width", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_width, class: "form-control no-border-radius" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :itm_height, "Height", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :itm_height, class: "form-control no-border-radius" %>
        </div>
    </div>
    
    <% if current_user.admin? %>
    <div class="form-group">
        <%= f.label :resource_state, I18n.t(:status).titleize, class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.select :resource_state, resource_states(Document), { include_blank: true }, class: "form-control no-border-radius" %>
        </div>
    </div>
    <% end %>

    <div class="form-group">
        <%= f.label :completion_date, "Completion Date", class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.datetime_local_field :completion_date, class: "form-control no-border-radius" %>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :signature, class: "form-label control-label col-md-2" %>
        <div class="col-md-10 no-padding">
            <%= f.text_field :signature, class: "form-control no-border-radius" %>
        </div>
    </div>

    <%= render 'shared/nested/remove_button', f: f %>
</div>

app/views/documents/_form.html.erb
<div class="well background-lighter-grey">
  <%= form_for @document, url: @document.persisted? ? flexible_resource_path(:document_path, @document) : documents_path do |f| %>
    <%= render 'shared/error_messages', object: @document %>

    <%= render 'document_fields', f: f %>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<div>

app/views/documents/_index.html.erb
<div class="row">
  <div class="col-md-10">
    <p class="text-align-left font-size-200 text-bold" >Documents</p>
  </div>

    <%= link_to new_document_path("projects", @project)  do %>
    <%= fa_icon "plus", class: "btn btn-info buffer-margin-10" %>
    <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created By</th>
      <th>Create At</th>
      <th>Status</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @project.documents.each do |document| %>
      <%= render "shared/display_models", object: document %>
    <% end %>
  </tbody>
</table>

app/views/documents/edit.html.erb
<% title('Editing Document titled ' + @document.title) %>
<%= content_tag :h1, 'Editing Document titled ' + @document.title %>

<%= render 'form', document: @document %>

<%= link_to 'Show', flexible_resource_path(:document_path, @document) %> |
<%= link_to 'Back', @resource %>

app/views/documents/index.html.erb
<% title('Documents') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <h1 class="no-margin">Documents</h1>
    </div>
  
    <div class="col-md-2 text-center">
      <%= link_to (params[:id] || params[:resource_id]).present? ? new_nested_document_path(params[:resource_controller] || controller_name, params[:id] || params[:resource_id]) : new_document_path do %>
        <%= fa_icon "plus", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created By</th>
      <th>Create At</th>
      <th>Status</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <%= render @documents %>
  </tbody>
</table>

app/views/documents/new.html.erb
<% title('New Document') %>
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', @resource %>

app/views/documents/show.html.erb
<% title('Document titled ' + @document.title) %>
<%= content_tag :h1, 'Document titled ' + @document.title %>

<div class="container-fluid">
  <p>
    <strong>Title:</strong>
    <%= @document.title %>
  </p>
  
  <p>
    <%= render "shared/resource_state_actions", 
                object: @document, 
                button_class: "btn btn-default col-md-offset-4 col-md-4 buffer-margin-10" %>
  </p>
</div>

<%= link_to "Edit", flexible_resource_path(:edit_document_path, @document) %> |
<%= link_to 'Back', @resource %>